module.exports.REQUEST_HOST = 'http://tstar.3ceng.cn';//配置api地址 测试
// module.exports.REQUEST_HOST = 'https://star.3ceng.cn';//配置api地址  正式
const imgUrl = "http://image.3ceng.cn/icon/cstl";
module.exports.HORO = [
    {
        'cstl_id': 'ari',
        'zh': '白羊座',
        'en': 'Aries',
        'start': '03/21',
        'end': '04/19',
        'bigImg': imgUrl  + '/icon_ari_big.png',
        'smallImg': imgUrl + '/icon_ari_small.png',
        'img': imgUrl + '/img_ari.png',
        'bg': imgUrl + '/bg_ari.png',
        'home_icon': imgUrl + '/icon_ari_home.png',
        'home_active': imgUrl +'/icon_ari_active.png' 
    },
    {
        'cstl_id': 'tau',
        'zh': '金牛座',
        'en': 'Taurus',
        'start': '04/20',
        'end': '05/20',
        'bigImg': imgUrl + '/icon_tau_big.png',
        'smallImg': imgUrl + '/icon_tau_small.png',
        'img': imgUrl + '/img_tau.png',
        'bg': imgUrl + '/bg_tau.png',
        'home_icon': imgUrl + '/icon_tau_home.png',
        'home_active': imgUrl +'/icon_tau_active.png' 
    },
    {
        'cstl_id': 'gem',
        'zh': '双子座',
        'en': 'Genimi',
        'start': '05/21',
        'end': '06/21',
        'bigImg': imgUrl + '/icon_gem_big.png',
        'smallImg': imgUrl + '/icon_gem_small.png',
        'img': imgUrl + '/img_gem.png',
        'bg': imgUrl + '/bg_gem.png',
        'home_icon': imgUrl + '/icon_gem_home.png',
        'home_active': imgUrl +'/icon_gem_active.png' 
    },
    {
        'cstl_id': 'cnc',
        'zh': '巨蟹座',
        'en': 'Cancer',
        'start': '06/22',
        'end': '07/22',
        'bigImg': imgUrl + '/icon_cnc_big.png',
        'smallImg': imgUrl + '/icon_cnc_small.png',
        'img': imgUrl + '/img_cnc.png',
        'bg': imgUrl + '/bg_cnc.png',
        'home_icon': imgUrl + '/icon_cnc_home.png',
        'home_active': imgUrl +'/icon_cnc_active.png' 
    },
    {
        'cstl_id': 'leo',
        'zh': '狮子座',
        'en': 'Leonis',
        'start': '07/23',
        'end': '08/22',
        'bigImg': imgUrl + '/icon_leo_big.png',
        'smallImg': imgUrl + '/icon_leo_small.png',
        'img': imgUrl + '/img_leo.png',
        'bg': imgUrl + '/bg_leo.png',
        'home_icon': imgUrl + '/icon_leo_home.png',
        'home_active': imgUrl +'/icon_leo_active.png' 
    },
    {
        'cstl_id': 'vir',
        'zh': '处女座',
        'en': 'Virgo',
        'start': '08/23',
        'end': '09/22',
        'bigImg': imgUrl + '/icon_vir_big.png',
        'smallImg': imgUrl + '/icon_vir_small.png',
        'img': imgUrl + '/img_vir.png',
        'bg': imgUrl + '/bg_vir.png',
        'home_icon': imgUrl + '/icon_vir_home.png',
        'home_active': imgUrl +'/icon_vir_active.png' 
    },
    {
        'cstl_id': 'lib',
        'zh': '天秤座',
        'en': 'Libra',
        'start': '09/23',
        'end': '10/23',
        'bigImg': imgUrl + '/icon_lib_big.png',
        'smallImg': imgUrl + '/icon_lib_small.png',
        'img': imgUrl + '/img_lib.png',
        'bg': imgUrl + '/bg_lib.png',
        'home_icon': imgUrl + '/icon_lib_home.png',
        'home_active': imgUrl +'/icon_lib_active.png' 
    },
    {
        'cstl_id': 'sco',
        'zh': '天蝎座',
        'en': 'Scorpius',
        'start': '10/24',
        'end': '11/22',
        'bigImg': imgUrl + '/icon_sco_big.png',
        'smallImg': imgUrl + '/icon_sco_small.png',
        'img': imgUrl + '/img_sco.png',
        'bg': imgUrl + '/bg_sco.png',
        'home_icon': imgUrl + '/icon_sco_home.png',
        'home_active': imgUrl +'/icon_sco_active.png' 
    },
    {
        'cstl_id': 'sgr',
        'zh': '射手座',
        'en': 'Sagittarius',
        'start': '11/23',
        'end': '12/21',
        'bigImg': imgUrl + '/icon_sgr_big.png',
        'smallImg': imgUrl + '/icon_sgr_small.png',
        'img': imgUrl + '/img_sgr.png',
        'bg': imgUrl + '/bg_sgr.png',
        'home_icon': imgUrl + '/icon_sgr_home.png',
        'home_active': imgUrl +'/icon_sgr_active.png' 
    },
    {
        'cstl_id': 'cap',
        'zh': '摩羯座',
        'en': 'Capricornus',
        'start': '12/22',
        'end': '01/19',
        'bigImg': imgUrl + '/icon_cap_big.png',
        'smallImg': imgUrl + '/icon_cap_small.png',
        'img': imgUrl + '/img_cap.png',
        'bg': imgUrl + '/bg_cap.png',
        'home_icon': imgUrl + '/icon_cap_home.png',
        'home_active': imgUrl +'/icon_cap_active.png' 
    },
    {
        'cstl_id': 'agr',
        'zh': '水瓶座',
        'en': 'Aguarius',
        'start': '01/20',
        'end': '02/18',
        'bigImg': imgUrl + '/icon_agr_big.png',
        'smallImg': imgUrl + '/icon_agr_small.png',
        'img': imgUrl + '/img_agr.png',
        'bg': imgUrl + '/bg_agr.png',
        'home_icon': imgUrl + '/icon_agr_home.png',
        'home_active': imgUrl +'/icon_agr_active.png' 
    },
    {
        'cstl_id': 'psc',
        'zh': '双鱼座',
        'en': 'Pisces',
        'start': '02/19',
        'end': '03/20',
        'bigImg': imgUrl + '/icon_psc_big.png',
        'smallImg': imgUrl + '/icon_psc_small.png',
        'img': imgUrl + '/img_psc.png',
        'bg': imgUrl + '/bg_psc.png',
        'home_icon': imgUrl + '/icon_psc_home.png',
        'home_active': imgUrl +'/icon_psc_active.png' 
    }
];